"""empty message

Revision ID: 11bef9ee8a01
Revises: 1dc87036b1a5
Create Date: 2014-09-08 07:16:43.231000

"""

# revision identifiers, used by Alembic.
revision = '11bef9ee8a01'
down_revision = '1dc87036b1a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
