"""empty message

Revision ID: 38f4ed38b081
Revises: None
Create Date: 2014-09-03 07:29:18.649000

"""

# revision identifiers, used by Alembic.
revision = '38f4ed38b081'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_time', sa.DateTime(), nullable=True),
    sa.Column('white_id', sa.Integer(), nullable=True),
    sa.Column('black_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('wtime', sa.String(length=8), nullable=True),
    sa.Column('btime', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['black_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['white_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('user')
    ### end Alembic commands ###
