"""empty message

Revision ID: 4e1d3fc4370b
Revises: 1c8833155696
Create Date: 2014-09-05 07:16:15.692000

"""

# revision identifiers, used by Alembic.
revision = '4e1d3fc4370b'
down_revision = '1c8833155696'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
