"""empty message

Revision ID: 1c8833155696
Revises: 38f4ed38b081
Create Date: 2014-09-03 07:43:02.138000

"""

# revision identifiers, used by Alembic.
revision = '1c8833155696'
down_revision = '38f4ed38b081'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
