"""empty message

Revision ID: 1dc87036b1a5
Revises: 15f93ea5fd51
Create Date: 2014-09-08 07:15:01.183000

"""

# revision identifiers, used by Alembic.
revision = '1dc87036b1a5'
down_revision = '15f93ea5fd51'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('wtime', sa.String(length=8), nullable=True),
    sa.Column('btime', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('white', sa.String(length=20), nullable=True),
    sa.Column('black', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['black'], ['users.username'], ),
    sa.ForeignKeyConstraint(['white'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('games')
    op.drop_table('user')
    op.drop_table('result')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), server_default="nextval('result_id_seq'::regclass)", nullable=False),
    sa.Column('rec_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wtime', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('btime', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'result_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default="nextval('user_id_seq'::regclass)", nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('games',
    sa.Column('results_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('white_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('black_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['black_id'], [u'user.id'], name=u'games_black_id_fkey'),
    sa.ForeignKeyConstraint(['results_id'], [u'result.id'], name=u'games_results_id_fkey'),
    sa.ForeignKeyConstraint(['white_id'], [u'user.id'], name=u'games_white_id_fkey')
    )
    op.drop_table('results')
    op.drop_table('users')
    ### end Alembic commands ###
