"""empty message

Revision ID: 1eb7a60710c2
Revises: 11bef9ee8a01
Create Date: 2014-09-08 07:19:31.321000

"""

# revision identifiers, used by Alembic.
revision = '1eb7a60710c2'
down_revision = '11bef9ee8a01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
