"""empty message

Revision ID: 3001ba805ff4
Revises: 1eb7a60710c2
Create Date: 2014-09-08 07:27:38.943000

"""

# revision identifiers, used by Alembic.
revision = '3001ba805ff4'
down_revision = '1eb7a60710c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
