"""empty message

Revision ID: 51270e9e6fc6
Revises: 3001ba805ff4
Create Date: 2014-09-09 06:50:13.016000

"""

# revision identifiers, used by Alembic.
revision = '51270e9e6fc6'
down_revision = '3001ba805ff4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
